packageExtensions:
  apollo-codegen-core@*:
    peerDependencies:
      graphql: "*"
  apollo-codegen-flow@*:
    peerDependencies:
      graphql: "*"
  apollo-codegen-scala@*:
    peerDependencies:
      graphql: "*"
  apollo-codegen-swift@*:
    peerDependencies:
      graphql: "*"
  apollo-codegen-typescript@*:
    peerDependencies:
      graphql: "*"
  apollo-datasource-rest@*:
    peerDependencies:
      graphql: "*"
  apollo-link-context@*:
    peerDependencies:
      graphql: "*"
  apollo-link-error@*:
    peerDependencies:
      graphql: "*"

yarnPath: .yarn/releases/yarn-3.1.1.cjs
